#
# Idra - Open Data Federation Platform
# Copyright (C) 2018 Engineering Ingegneria Informatica S.p.A.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '3'
services :
    db:
            image: mysql:5.7
            restart: always
            ports:
                - 3306:3306
            volumes:
                - ./opt/idra/mysql-data:/var/lib/mysql
                - ./idra_db.sql:/docker-entrypoint-initdb.d/idra_db.sql
            networks:
                idra_main:
            environment:
                - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/my_secret_data
                - MYSQL_DATABASE=idra_db
            secrets:
                - my_secret_data
                
            command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    rdf4j:
            image: yyz1989/rdf4j
            ports:
                - 8081:8080
            volumes:
                - ./opt/idra/rdf4j-data:/opt/rdf4j/data
            environment:
                - RDF4J_DATA=/opt/rdf4j/data
            networks:
                idra_main:  
    idra:
            build: .
            ports:
                - 8080:8080
            depends_on: 
                - db
                # - rdf4j
            command: ["./wait-for-it.sh", "db:3306", "--timeout=0", "--", "catalina.sh", "run"]
            
            environment:
                - idra.db.host=jdbc:mysql://db:3306/idra_db?serverTimezone=UTC&useLegacyDatetimeCode=false&useEncoding=true&characterEncoding=UTF-8&useSSL=false
                - idra.db.host.min=jdbc:mysql://db:3306
                - idra.db.user_FILE=/run/secrets/my_secret_data
                - idra.db.password_FILE=/run/secrets/my_secret_data
                - idra.db.name=idra_db
                - idra.cache.loadfromdb=true
                - idra.synch.onstart=false
                - idra.odms.dump.file.path=/opt/idra/dump/
                - idra.dump.file.path=/opt/idra/dump/
                - idra.lod.enable=true
                - idra.lod.repo.name=Idra
                - idra.lod.server.uri=http://rdf4j:8080/rdf4j-server/repositories/
                - idra.lod.server.uri.query=http://rdf4j:8080/rdf4j-workbench/repositories/Idra/query
                - idra.orion.orionDumpFilePath=/opt/idra/dump/
                - idra.orion.orionInternalAPI=http://IDRA_HOST/Idra/api/v1/client/executeOrionQuery
                - idra.authentication.method=BASIC
                - idm.fiware.version=7
                - idm.protocol=https
                - idm.host=
                - idm.path.base=
                - idm.client.id=
                - idm.client.secret=
                - idm.redirecturi=http://IDRA_HOST/Idra/api/v1/administration/login
                - idm.logout.callback=http://IDRA_HOST/IdraPortal
                - idm.admin.role.name=Admin
                - idra.server.baseurl=<IDRA_PROTOCOL>://<IDRA_HOST>
                - JAVA_OPTS=-Xms1024m -Xmx3g -XX:PermSize=1024m -XX:MaxPermSize=2048m
            secrets:
                - my_secret_data             
            volumes:
                - ./opt/idra/dump:/opt/idra/dump
                - /dev/urandom:/dev/random
            networks:
                idra_main:
                
networks:
    idra_main:
          driver: bridge
          
secrets:
  my_secret_data:
    file: ./docker/secrets.txt