site_name: Idra
site_url: https://idra.readthedocs.org
repo_url: https://github.com/OPSILab/Idra
site_description: Idra - Open Data Federation platform Documentation
docs_dir: docs/manuals
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: true
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_publication.css"]

pages:
  - 'Home': 'manuals/index.md' 
  - 'Architecture Overview': 'manuals/architecture/architecture.md'
  - 'Installation & Administration Manual':
      - 'Introduction': 'manuals/admin/index.md'
      - 'Installation overview': 'manuals/admin/installation.md'
      - 'Install with WARs packages': 'manuals/admin/install_war.md'
      - 'Install with Docker': 'manuals/admin/install_docker.md'
      - 'Sanity Checks': 'manuals/admin/sanitychecks.md'
      - 'Platform Management': 'manuals/admin/administration_gui.md'
  - 'User Guide':
      - 'Introduction': 'manuals/user/index.md'
      - 'How to use Idra': 'manuals/user/enduser.md'
