package it.eng.idra.beans.dcat;

public enum DCTFrequency {

	ANNUAL, ANNUAL_2, ANNUAL_3, BIENNIAL, BIMONTHLY, BIWEEKLY, CONT, DAILY, DAILY_2, IRREG, MONTHLY, MONTHLY_2,
	MONTHLY_3, NEVER, OP_DATPRO, QUARTERLY, TRIENNIAL, UNKNOWN, UPDATE_CONT, WEEKLY_2, WEEKLY_3, DECENNIAL, HOURLY,
	QUADRENNIAL, QUINQUENNIAL;
}
